# Generated by Django 2.1.5 on 2019-01-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('notepad', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Users2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('login', models.TextField()),
                ('password', models.TextField()),
                ('notepad', models.TextField()),
            ],
        ),
    ]
