# Generated by Django 2.1.2 on 2018-11-11 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LogErrors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errorslogs',
            name='Date',
            field=models.TextField(),
        ),
    ]
