# Generated by Django 2.1.3 on 2018-11-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DialogueBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.TextField()),
                ('when', models.CharField(max_length=100)),
                ('what', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='DialoguesBD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('who', models.CharField(max_length=100)),
                ('which', models.TextField()),
            ],
        ),
    ]
